smo_platform_home:
    path:       /{page}
    defaults:   { _controller: SMOPlatformBundle:Advert:index, page: 1 }
    requirements:
        page:   \d*

smo_platform_view:
    path:       /advert/{id}
    defaults:   { _controller: SMOPlatformBundle:Advert:view }
    requirements:
        id:     \d+

smo_platform_add:
    path:       /add
    defaults:   { _controller: SMOPlatformBundle:Advert:add }

smo_platform_edit:
    path:       /edit/{id}
    defaults:   { _controller: SMOPlatformBundle:Advert:edit }
    requirements:
        id:     \d+

smo_platform_delete:
    path:       /delete/{id}
    defaults:   { _controller: SMOPlatformBundle:Advert:delete }
    requirements:
        id:     \d+

smo_platform_jquery:
    path:       /jquery
    defaults:   { _controller: SMOPlatformBundle:Advert:jquery }