parameters:
    mon_parametre: ma_valeur

services:

    smo_platform.doctrine.notification:
        class: SMO\PlatformBundle\DoctrineListener\ApplicationNotification
        arguments: [@mailer]
        tags:
            - { name: doctrine.event_listener, event: postPersist }
    
    smo_platform.antispam:
        class: SMO\PlatformBundle\Antispam\SMOAntispam
        arguments: [@mailer, 50]
        calls:
            - [ setLocale, [%locale% ] ]
#        tags:
#            - { name: twig.extension }
     
    smo_platform.validator.antiflood:
        class: SMO\PlatformBundle\Validator\AntifloodValidator
        arguments: [@request_stack, @doctrine.orm.entity_manager]
        tags:
            - { name: validator.constraint_validator, alias: smo_platform_antiflood }
            
    smo_blog.ckeditor:
        class: SMO\PlatformBundle\Form\Type\CkeditorType
        tags:
            - { name: form.type, alias: ckeditor }