parameters:
    mon_parametre: ma_valeur

services:

    smo_platform.doctrine.notification:
        class: SMO\PlatformBundle\DoctrineListener\ApplicationNotification
        arguments: [@mailer]
        tags:
            - { name: doctrine.event_listener, event: postPersist }
    
    smo_platform.antispam:
        class: SMO\PlatformBundle\Antispam\SMOAntispam
        arguments: [@mailer, %locale%, 50]