parameters:
    mon_parametre: ma_valeur

services:
    smo_platform.beta.html:
        class: SMO\PlatformBundle\Beta\BetaHTML
        
    smo_platform.beta.listener:
        class: SMO\PlatformBundle\Beta\BetaListener
        arguments: [@smo_platform.beta.html, "2015-09-05"]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: processBeta, priority: 2 }

    smo_platform.censorship_processor:
        class: SMO\PlatformBundle\Bigbrother\CensorshipProcessor
        arguments: [@mailer]

    smo_platform.censorship_listener:
        class: SMO\PlatformBundle\Bigbrother\CensorshipListener
        arguments: [@smo_platform.censorship_processor, [1,2,3]]
        tags:
            - { name: kernel.event_subsciber }

    
    smo_platform.doctrine.notification:
        class: SMO\PlatformBundle\DoctrineListener\ApplicationNotification
        arguments: [@mailer]
        tags:
            - { name: doctrine.event_listener, event: postPersist }
    
    smo_platform.antispam:
        class: SMO\PlatformBundle\Antispam\SMOAntispam
        arguments: [@mailer, 50]
#        calls:
#            - [ setLocale, [%locale% ] ]
#        tags:
#            - { name: twig.extension }
     
    smo_platform.validator.antiflood:
        class: SMO\PlatformBundle\Validator\AntifloodValidator
        arguments: [@request_stack, @doctrine.orm.entity_manager]
#        tags:
#            - { name: validator.constraint_validator, alias: smo_platform_antiflood }
            
    smo_blog.ckeditor:
        class: SMO\PlatformBundle\Form\Type\CkeditorType
#        tags:
#            - { name: form.type, alias: ckeditor }

    smo_platform.json_paramconverter:
        class: SMO\PlatformBundle\ParamConverter\JsonParamConverter
        tags:
            - { name: request.param_converter }