smo_platform:
    resource: "@SMOPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform

login:
    pattern:    /login
    defaults:   { _controller: SMOUserBundle:Security:login }
    
login_check:
    pattern:    /login_check
    
logout:
    pattern:    /logout