<?php

namespace SMO\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends EntityRepository
{
    public function myFindAll()
    {
        return $this
            ->createQueryBuilder()
            ->getQuery()
            ->getResult()
        ;
    }
    
    public function myFindId($id)
    {
        $qd = $this->createQueryBuilder('a');
        
        $qd
            ->where('a.id = :id')
              ->setParameter('id', $id)
        ;
        
        return $qd
            ->getQuery()
            ->getResult()
        ;
    }
    
    public function findByAuthorAndDate($author, $year)
    {
        $qd = $this->createQueryBuilder();
        
        $qd
            ->where('a.author = :author')
              ->setParameter('author', $author)
            ->andWhere('a.date < :year')
              ->setParameter('year', $year)
            ->orderBy('a.date', 'DESC')
        ;
        
        return $qd
            ->getQuery()
            ->getResult()
        ;
    }
}
