<?php
// srv/SMO/PlatformBundle/Entity/AdvertRepository.php

namespace SMO\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends EntityRepository
{
    public function getAdverts($page = 1, $nbPerPage)
    {
        $query = $this
            ->createQueryBuilder('a')
            // Jointure sur l'attribut image
            ->leftJoin('a.image', 'i')
            ->addSelect('i')
            // Jointure sur l'attribut categories
            ->leftJoin('a.categories', 'c')
            ->addSelect('c')
            // Jointure sur l'attribut advertSkills
            ->leftJoin('a.advertSkills', 'ads')
            ->addSelect('ads')
            ->orderBy('a.date', 'DESC')
            ->getQuery()
        ;
        
        $query
            // A partir de quelle annonce on commence la liste
            ->setFirstResult(($page - 1) * $nbPerPage)
            // Nombre maxium de résultat à afficher
            ->setMaxResults($nbPerPage)
        ;
        
        // On utilise la fonction de pagination de Doctrine
        // Retourne les annonces ET le nombre d'annonce totale sans le MAX
        return new Paginator($query, true);
    }
    
    
}
