<?php

namespace SMO\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends EntityRepository
{
    public function getApplicationWithAdvert($limit)
    {
        $qd = $this
            ->createQueryBuilder('a')
            ->leftJoin('a.advert', 'adv')
            ->addSelect('adv')
            ->setMaxResults($limit)
        ;
        
        return $qd
            ->getQuery()
            ->getResult()
        ;
    }
}
